In [1]:
import pandas as pd
from chanlun.backtesting import backtest
from chanlun.strategy import strategy_demo
from chanlun.cl_utils import query_cl_chart_config

欢迎使用缠论数据计算工具；
项目地址：https://github.com/yijixiuxin/chanlun-pro
授权许可有效期：2099-01-01

在使用天勤量化之前，默认您已经知晓并同意以下免责条款，如果不同意请立即停止使用：https://www.shinnytech.com/blog/disclaimer/

## 注意事项
回测前要确保已经同步回测时间段内的行情数据到数据库中

同步行情数据请参考 /script/crontab/ 目录下的脚本

In [2]:
# 量化配置
bt_config = {
    # 策略结果保存的文件
    'save_file': './data/bk/futures_strategy_demo.pkl',
    # 设置策略对象
    'strategy': strategy_demo.StrategyDemo(),
    # 回测模式：signal 信号模式，固定金额开仓； trade 交易模式，按照实际金额开仓
    'mode': 'signal',
    # 市场配置，currency 数字货币  a 沪深  hk  港股  futures  期货
    'market': 'futures',
    # 基准代码，用于获取回测的时间列表
    'base_code': 'SHFE.ag2206',
    # 回测的标的代码
    'codes': ['SHFE.ag2206'],
    # 回测的周期，这里设置里，在策略中才能取到对应周期的数据
    'frequencys': ['5m'],
    # 回测开始的时间
    'start_datetime': '2022-02-01 00:00:00',
    # 回测的结束时间
    'end_datetime': '2022-03-01 00:00:00',
    # mode 为 trade 生效，初始账户资金
    'init_balance': 1000000,
    # mode 为 trade 生效，交易手续费率
    'fee_rate': 0.0006,
    # mode 为 trade 生效，最大持仓数量（分仓）
    'max_pos': 2,
    # 缠论计算的配置，详见缠论配置说明
    'cl_config': query_cl_chart_configy('futures', 'SHFE.RB'),
}

BT = backtest.BackTest(bt_config)
BT.datas.load_data_to_cache = True # 是否将所有k线数据加载到内存中，如果内存吃紧，可以设置为 False，这样每次循环都会从数据库中读取
BT.datas.load_kline_nums = 10000 # 每次 klines 方法中返回的k线数据条数
BT.datas.cl_data_kline_max_nums = 30000 # 回测过程中，如果缠论对象的数据量超过这个值，则会清空重新计算，cl_data_kline_max_nums 不能小于 load_kline_nums，否则将会不断的删除并重新计算

In [3]:
# 运行回测
BT.run()
# 多进程回测，只支持信号回测模式
# BT.run_process(max_workers=4)
# 保存回测结果到文件中
BT.save()
print('Done')

[SHFE.ag2206 - 2022-02-07 23:00:00] // 3buy 做多买入（4781.0 - 20.707），原因： 当前级别 (MMD: ['3buy'] Loss: 4767.0)
[SHFE.ag2206 - 2022-02-08 09:00:00] // 3buy 平仓做多（4798.0 - 20.707） 盈亏：352.01900000000023  (0.36%)，原因： 3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False, QS: False）），多仓清仓
[SHFE.ag2206 - 2022-02-08 23:00:00] // 3buy 做多买入（4822.0 - 20.5309），原因： 当前级别 (MMD: ['3buy'] Loss: 4783.0)
[SHFE.ag2206 - 2022-02-09 00:00:00] // 3buy 平仓做多（4819.0 - 20.5309） 盈亏：-61.59269999999378  (-0.06%)，原因： 3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False, QS: False）），多仓清仓
[SHFE.ag2206 - 2022-02-12 01:00:00] // 3buy 做多买入（4816.0 - 20.5565），原因： 当前级别 (MMD: ['3buy'] Loss: 4799.0)
[SHFE.ag2206 - 2022-02-12 01:50:00] // 3buy 平仓做多（4820.0 - 20.5565） 盈亏：82.22600000000966  (0.08%)，原因： 3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False, QS: False）），多仓清仓
[SHFE.ag2206 - 2022-02-14 13:55:00] // 3buy 做多买入（4904.0 - 20.1876），原因： 当前级别 (MMD: ['3buy'] Loss: 4892.0)
[SHFE.ag2206 - 2022-02-14 21:05:00] // l3buy 做多买入（4913.0 - 20.1506），原因： 当前级别 (MMD: ['l3buy'] Loss: 4898.0)
[SHFE.ag2206 - 2022-02-15 11:20:00] // 3buy 平仓做多（4941.0 - 20.1876） 盈亏：746.9412000000011  (0.75%)，原因： 3buy 当前级别出现卖点（MMDS: ['1sell']，BC：（BI: True, PZ: False, QS: True）），多仓清仓
[SHFE.ag2206 - 2022-02-15 11:20:00] // l3buy 平仓做多（4941.0 - 20.1506） 盈亏：564.2167999999947  (0.57%)，原因： l3buy 当前级别出现卖点（MMDS: ['1sell']，BC：（BI: True, PZ: False, QS: True）），多仓清仓
[SHFE.ag2206 - 2022-02-15 11:20:00] // 1sell 做空卖出（4941.0 - 20.0364），原因： 当前级别 (MMD: ['1sell'] Loss: 4964.0)
[SHFE.ag2206 - 2022-02-15 22:15:00] // 1sell 平仓做空（4797.0 - 20.0364） 盈亏：2885.2416000000085 (2.91%)，原因： 1sell 当前级别出现买点（MMDS: ['l3buy']，BC：（BI: False, PZ: False, QS: False）），空仓清仓
[SHFE.ag2206 - 2022-02-15 22:15:00] // l3buy 做多买入（4797.0 - 20.6379），原因： 当前级别 (MMD: ['l3buy'] Loss: 4780.0)
[SHFE.ag2206 - 2022-02-16 00:25:00] // l3buy 平仓做多（4793.0 - 20.6379） 盈亏：-82.55160000000615  (-0.08%)，原因： l3buy 当前级别出现卖点（MMDS: ['3sell']，BC：（BI: False, PZ: False, QS: False）），多仓清仓
[SHFE.ag2206 - 2022-02-16 00:25:00] // 3sell 做空卖出（4793.0 - 20.6551），原因： 当前级别 (MMD: ['3sell'] Loss: 4802.0)
[SHFE.ag2206 - 2022-02-16 00:40:00] // l3buy 做多买入（4801.0 - 20.6207），原因： 当前级别 (MMD: ['l3buy'] Loss: 4777.0)
[SHFE.ag2206 - 2022-02-16 00:55:00] // 3sell 平仓做空（4804.0 - 20.6551） 盈亏：-227.20610000001034 (-0.23%)，原因： 3sell 止损
[SHFE.ag2206 - 2022-02-16 01:15:00] // l3buy 平仓做多（4801.0 - 20.6207） 盈亏：0.0  (0.00%)，原因： l3buy 当前级别出现卖点（MMDS: ['3sell']，BC：（BI: False, PZ: False, QS: False）），多仓清仓
[SHFE.ag2206 - 2022-02-16 01:15:00] // 3sell 做空卖出（4801.0 - 20.6207），原因： 当前级别 (MMD: ['3sell'] Loss: 4808.0)
[SHFE.ag2206 - 2022-02-16 02:15:00] // 3sell 平仓做空（4811.0 - 20.6207） 盈亏：-206.20699999999488 (-0.21%)，原因： 3sell 止损
[SHFE.ag2206 - 2022-02-17 22:35:00] // 3buy 做多买入（4873.0 - 20.316），原因： 当前级别 (MMD: ['3buy'] Loss: 4857.0)
[SHFE.ag2206 - 2022-02-18 09:40:00] // 3buy 平仓做多（4886.0 - 20.316） 盈亏：264.10800000000745  (0.27%)，原因： 3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False, QS: False）），多仓清仓
[SHFE.ag2206 - 2022-02-18 21:50:00] // 2sell 做空卖出（4925.0 - 20.1015），原因： 当前级别 (MMD: ['2sell'] Loss: 4945.0)
[SHFE.ag2206 - 2022-02-18 22:45:00] // 2sell 平仓做空（4925.0 - 20.1015） 盈亏：0.0 (0.00%)，原因： 2sell 当前级别出现买点（MMDS: ['3buy']，BC：（BI: False, PZ: False, QS: False）），空仓清仓
[SHFE.ag2206 - 2022-02-18 22:45:00] // 3buy 做多买入（4925.0 - 20.1015），原因： 当前级别 (MMD: ['3buy'] Loss: 4905.0)
[SHFE.ag2206 - 2022-02-21 09:15:00] // 3buy 平仓做多（4890.0 - 20.1015） 盈亏：-703.5525000000052  (-0.71%)，原因： 3buy 止损
[SHFE.ag2206 - 2022-02-21 13:40:00] // 3sell 做空卖出（4877.0 - 20.2994），原因： 当前级别 (MMD: ['3sell'] Loss: 4904.0)
[SHFE.ag2206 - 2022-02-21 14:45:00] // 3sell 平仓做空（4873.0 - 20.2994） 盈亏：81.19759999999951 (0.08%)，原因： 3sell 当前级别出现买点（MMDS: []，BC：（BI: True, PZ: False, QS: False）），空仓清仓
[SHFE.ag2206 - 2022-02-22 10:55:00] // 3buy 做多买入（4959.0 - 19.9637），原因： 当前级别 (MMD: ['3buy'] Loss: 4916.0)
[SHFE.ag2206 - 2022-02-23 09:40:00] // 3buy 平仓做多（4964.0 - 19.9637） 盈亏：99.81849999999395  (0.10%)，原因： 3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False, QS: False）），多仓清仓
[SHFE.ag2206 - 2022-02-24 21:05:00] // 3buy 做多买入（5185.0 - 19.0935），原因： 当前级别 (MMD: ['3buy'] Loss: 5096.0)
[SHFE.ag2206 - 2022-02-24 21:50:00] // 3buy 平仓做多（5163.0 - 19.0935） 盈亏：-420.0570000000007  (-0.42%)，原因： 3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False, QS: False）），多仓清仓
[SHFE.ag2206 - 2022-02-25 01:25:00] // l3buy 做多买入（5057.0 - 19.5768），原因： 当前级别 (MMD: ['l3buy'] Loss: 5026.0)
[SHFE.ag2206 - 2022-02-25 02:10:00] // l3buy 平仓做多（5049.0 - 19.5768） 盈亏：-156.61440000000584  (-0.16%)，原因： l3buy 当前级别出现卖点（MMDS: ['3sell']，BC：（BI: False, PZ: False, QS: False）），多仓清仓
[SHFE.ag2206 - 2022-02-25 02:10:00] // 3sell 做空卖出（5049.0 - 19.6078），原因： 当前级别 (MMD: ['3sell'] Loss: 5061.0)
[SHFE.ag2206 - 2022-02-25 14:25:00] // 3sell 平仓做空（4978.0 - 19.6078） 盈亏：1392.1538 (1.41%)，原因： 3sell 当前级别出现买点（MMDS: []，BC：（BI: True, PZ: False, QS: False）），空仓清仓
运行完成，执行时间：8.329020023345947
save to : ./data/bk/futures_strategy_demo.pkl

Done

In [4]:
# 输出回测结果
BT.info()
BT.result()

2022-05-04 19:16:27
Save File : ./data/bk/futures_strategy_demo.pkl
Mode signal init balance 1000000 fee rate 0.0006
is stock False is futures True
STR Class : <chanlun.strategy.strategy_demo.StrategyDemo object at 0x000001FE479AE9C8>
Base Code : SHFE.ag2206
Run Codes : ['SHFE.ag2206']
Frequencys : ['5m']
Start time : 2022-02-01 00:00:00 End time : 2022-03-01 00:00:00
CL Config : {'xd_bzh': 'xd_bzh_no', 'fx_qj': 'fx_qj_k', 'fx_bh': 'fx_bh_dingdi', 'bi_type': 'bi_type_new', 'bi_bzh': 'bi_bzh_yes', 'bi_qj': 'bi_qj_ck', 'bi_fx_cgd': 'bi_fx_cgd_no', 'xd_qj': 'xd_qj_dd', 'zsd_bzh': 'zsd_bzh_yes', 'zsd_qj': 'zsd_qj_dd', 'zs_bi_type': 'zs_type_dn', 'zs_xd_type': 'zs_type_dn', 'zs_qj': 'zs_qj_dd', 'zs_wzgx': 'zs_wzgx_zgd', 'idx_macd_fast': 12, 'idx_macd_slow': 26, 'idx_macd_signal': 9, 'idx_boll_period': 20, 'idx_ma_period': 5}

+--------------+------+------+--------+---------+--------+---------+----------+----------+----------+--------+
|    买卖点    | 成功 | 失败 |  胜率  |   盈利  |  亏损  |  净利润 | 回吐比例 | 平均盈利 | 平均亏损 | 盈亏比 |
+--------------+------+------+--------+---------+--------+---------+----------+----------+----------+--------+
|   一类买点   |  0   |  0   |   0%   |    0    |   0    |    0    |    0     |    0     |    0     |   0    |
|   二类买点   |  0   |  0   |   0%   |    0    |   0    |    0    |    0     |    0     |    0     |   0    |
|  类二类买点  |  0   |  0   |   0%   |    0    |   0    |    0    |    0     |    0     |    0     |   0    |
|   三类买点   |  5   |  3   | 62.5%  | 1545.11 | 1185.2 |  359.91 |  76.71   |  309.02  |  395.07  | 0.7822 |
|  类三类买点  |  1   |  3   | 25.0%  |  564.22 | 239.17 |  325.05 |  42.39   |  564.22  |  79.72   | 7.0773 |
| 下跌盘整背驰 |  0   |  0   |   0%   |    0    |   0    |    0    |    0     |    0     |    0     |   0    |
| 下跌趋势背驰 |  0   |  0   |   0%   |    0    |   0    |    0    |    0     |    0     |    0     |   0    |
|   一类卖点   |  1   |  0   | 100.0% | 2885.24 |   0    | 2885.24 |   0.0    | 2885.24  |    0     |   0    |
|   二类卖点   |  0   |  1   |  0.0%  |    0    |  0.0   |   0.0   |    0     |    0     |   0.0    |   0    |
|  类二类卖点  |  0   |  0   |   0%   |    0    |   0    |    0    |    0     |    0     |    0     |   0    |
|   三类卖点   |  2   |  2   | 50.0%  | 1473.35 | 433.41 | 1039.94 |  29.42   |  736.68  |  216.71  | 3.3994 |
|  类三类卖点  |  0   |  0   |   0%   |    0    |   0    |    0    |    0     |    0     |    0     |   0    |
| 上涨盘整背驰 |  0   |  0   |   0%   |    0    |   0    |    0    |    0     |    0     |    0     |   0    |
| 上涨趋势背驰 |  0   |  0   |   0%   |    0    |   0    |    0    |    0     |    0     |    0     |   0    |
+--------------+------+------+--------+---------+--------+---------+----------+----------+----------+--------+

In [6]:
# 回测数据展示
BT.backtest_charts()

,code,mmd,open_datetime,close_datetime,type,price,amount,loss_price,profit_rate,max_profit_rate,max_loss_rate,open_msg,close_msg
0,SHFE.ag2206,3buy,2022-02-07 23:00:00,2022-02-08 09:00:00,做多,4781.0,20.7070,4767.0,0.36,0.5438,-0.2510,当前级别 (MMD: ['3buy'] Loss: 4767.0),"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
1,SHFE.ag2206,3buy,2022-02-08 23:00:00,2022-02-09 00:00:00,做多,4822.0,20.5309,4783.0,-0.06,0.2489,-0.1866,当前级别 (MMD: ['3buy'] Loss: 4783.0),"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
2,SHFE.ag2206,3buy,2022-02-12 01:00:00,2022-02-12 01:50:00,做多,4816.0,20.5565,4799.0,0.08,0.3530,-0.0623,当前级别 (MMD: ['3buy'] Loss: 4799.0),"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
3,SHFE.ag2206,3buy,2022-02-14 13:55:00,2022-02-15 11:20:00,做多,4904.0,20.1876,4892.0,0.75,1.2235,-0.1223,当前级别 (MMD: ['3buy'] Loss: 4892.0),"3buy 当前级别出现卖点（MMDS: ['1sell']，BC：（BI: True, PZ..."
4,SHFE.ag2206,l3buy,2022-02-14 21:05:00,2022-02-15 11:20:00,做多,4913.0,20.1506,4898.0,0.57,1.0381,-0.3053,当前级别 (MMD: ['l3buy'] Loss: 4898.0),"l3buy 当前级别出现卖点（MMDS: ['1sell']，BC：（BI: True, P..."
5,SHFE.ag2206,1sell,2022-02-15 11:20:00,2022-02-15 22:15:00,做空,4941.0,20.0364,4964.0,2.91,3.2584,-0.2429,当前级别 (MMD: ['1sell'] Loss: 4964.0),"1sell 当前级别出现买点（MMDS: ['l3buy']，BC：（BI: False, ..."
6,SHFE.ag2206,l3buy,2022-02-15 22:15:00,2022-02-16 00:25:00,做多,4797.0,20.6379,4780.0,-0.08,0.1042,-0.4169,当前级别 (MMD: ['l3buy'] Loss: 4780.0),"l3buy 当前级别出现卖点（MMDS: ['3sell']，BC：（BI: False, ..."
7,SHFE.ag2206,3sell,2022-02-16 00:25:00,2022-02-16 00:55:00,做空,4793.0,20.6551,4802.0,-0.23,0.0209,-0.3130,当前级别 (MMD: ['3sell'] Loss: 4802.0),3sell 止损
8,SHFE.ag2206,l3buy,2022-02-16 00:40:00,2022-02-16 01:15:00,做多,4801.0,20.6207,4777.0,0.00,0.1458,-0.0833,当前级别 (MMD: ['l3buy'] Loss: 4777.0),"l3buy 当前级别出现卖点（MMDS: ['3sell']，BC：（BI: False, ..."
9,SHFE.ag2206,3sell,2022-02-16 01:15:00,2022-02-16 02:15:00,做空,4801.0,20.6207,4808.0,-0.21,0.0417,-0.2499,当前级别 (MMD: ['3sell'] Loss: 4808.0),3sell 止损
10,SHFE.ag2206,3buy,2022-02-17 22:35:00,2022-02-18 09:40:00,做多,4873.0,20.3160,4857.0,0.27,0.7182,-0.3078,当前级别 (MMD: ['3buy'] Loss: 4857.0),"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
11,SHFE.ag2206,2sell,2022-02-18 21:50:00,2022-02-18 22:45:00,做空,4925.0,20.1015,4945.0,0.00,0.4061,-0.0609,当前级别 (MMD: ['2sell'] Loss: 4945.0),"2sell 当前级别出现买点（MMDS: ['3buy']，BC：（BI: False, P..."
12,SHFE.ag2206,3buy,2022-02-18 22:45:00,2022-02-21 09:15:00,做多,4925.0,20.1015,4905.0,-0.71,0.1827,-0.8528,当前级别 (MMD: ['3buy'] Loss: 4905.0),3buy 止损
13,SHFE.ag2206,3sell,2022-02-21 13:40:00,2022-02-21 14:45:00,做空,4877.0,20.2994,4904.0,0.08,0.2871,-0.2050,当前级别 (MMD: ['3sell'] Loss: 4904.0),"3sell 当前级别出现买点（MMDS: []，BC：（BI: True, PZ: Fals..."
14,SHFE.ag2206,3buy,2022-02-22 10:55:00,2022-02-23 09:40:00,做多,4959.0,19.9637,4916.0,0.10,0.9276,-0.5041,当前级别 (MMD: ['3buy'] Loss: 4916.0),"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
15,SHFE.ag2206,3buy,2022-02-24 21:05:00,2022-02-24 21:50:00,做多,5185.0,19.0935,5096.0,-0.42,0.1350,-0.5593,当前级别 (MMD: ['3buy'] Loss: 5096.0),"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
16,SHFE.ag2206,l3buy,2022-02-25 01:25:00,2022-02-25 02:10:00,做多,5057.0,19.5768,5026.0,-0.16,0.0791,-0.2571,当前级别 (MMD: ['l3buy'] Loss: 5026.0),"l3buy 当前级别出现卖点（MMDS: ['3sell']，BC：（BI: False, ..."
17,SHFE.ag2206,3sell,2022-02-25 02:10:00,2022-02-25 14:25:00,做空,5049.0,19.6078,5061.0,1.41,1.9014,-0.0396,当前级别 (MMD: ['3sell'] Loss: 5061.0),"3sell 当前级别出现买点（MMDS: []，BC：（BI: True, PZ: Fals..."

In [6]:
# 显示历史持仓
#设置显示全部行，不省略
pd.set_option('display.max_rows',None)
#设置显示全部列，不省略
pd.set_option('display.max_columns',None)

# 显示历史持仓
pos_df = BT.positions()
pos_df

,code,mmd,open_datetime,close_datetime,type,price,amount,loss_price,profit_rate,max_profit_rate,max_loss_rate,open_msg,close_msg
0,SHFE.ag2206,3buy,2022-02-07 23:00:00,2022-02-08 09:00:00,做多,4781.0,20.7070,4767.0,0.36,0.5438,-0.2510,当前级别 (MMD: ['3buy'] Loss: 4767.0),"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
1,SHFE.ag2206,3buy,2022-02-08 23:00:00,2022-02-09 00:00:00,做多,4822.0,20.5309,4783.0,-0.06,0.2489,-0.1866,当前级别 (MMD: ['3buy'] Loss: 4783.0),"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
2,SHFE.ag2206,3buy,2022-02-12 01:00:00,2022-02-12 01:50:00,做多,4816.0,20.5565,4799.0,0.08,0.3530,-0.0623,当前级别 (MMD: ['3buy'] Loss: 4799.0),"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
3,SHFE.ag2206,3buy,2022-02-14 13:55:00,2022-02-15 11:20:00,做多,4904.0,20.1876,4892.0,0.75,1.2235,-0.1223,当前级别 (MMD: ['3buy'] Loss: 4892.0),"3buy 当前级别出现卖点（MMDS: ['1sell']，BC：（BI: True, PZ..."
4,SHFE.ag2206,l3buy,2022-02-14 21:05:00,2022-02-15 11:20:00,做多,4913.0,20.1506,4898.0,0.57,1.0381,-0.3053,当前级别 (MMD: ['l3buy'] Loss: 4898.0),"l3buy 当前级别出现卖点（MMDS: ['1sell']，BC：（BI: True, P..."
5,SHFE.ag2206,1sell,2022-02-15 11:20:00,2022-02-15 22:15:00,做空,4941.0,20.0364,4964.0,2.91,3.2584,-0.2429,当前级别 (MMD: ['1sell'] Loss: 4964.0),"1sell 当前级别出现买点（MMDS: ['l3buy']，BC：（BI: False, ..."
6,SHFE.ag2206,l3buy,2022-02-15 22:15:00,2022-02-16 00:25:00,做多,4797.0,20.6379,4780.0,-0.08,0.1042,-0.4169,当前级别 (MMD: ['l3buy'] Loss: 4780.0),"l3buy 当前级别出现卖点（MMDS: ['3sell']，BC：（BI: False, ..."
7,SHFE.ag2206,3sell,2022-02-16 00:25:00,2022-02-16 00:55:00,做空,4793.0,20.6551,4802.0,-0.23,0.0209,-0.3130,当前级别 (MMD: ['3sell'] Loss: 4802.0),3sell 止损
8,SHFE.ag2206,l3buy,2022-02-16 00:40:00,2022-02-16 01:15:00,做多,4801.0,20.6207,4777.0,0.00,0.1458,-0.0833,当前级别 (MMD: ['l3buy'] Loss: 4777.0),"l3buy 当前级别出现卖点（MMDS: ['3sell']，BC：（BI: False, ..."
9,SHFE.ag2206,3sell,2022-02-16 01:15:00,2022-02-16 02:15:00,做空,4801.0,20.6207,4808.0,-0.21,0.0417,-0.2499,当前级别 (MMD: ['3sell'] Loss: 4808.0),3sell 止损
10,SHFE.ag2206,3buy,2022-02-17 22:35:00,2022-02-18 09:40:00,做多,4873.0,20.3160,4857.0,0.27,0.7182,-0.3078,当前级别 (MMD: ['3buy'] Loss: 4857.0),"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
11,SHFE.ag2206,2sell,2022-02-18 21:50:00,2022-02-18 22:45:00,做空,4925.0,20.1015,4945.0,0.00,0.4061,-0.0609,当前级别 (MMD: ['2sell'] Loss: 4945.0),"2sell 当前级别出现买点（MMDS: ['3buy']，BC：（BI: False, P..."
12,SHFE.ag2206,3buy,2022-02-18 22:45:00,2022-02-21 09:15:00,做多,4925.0,20.1015,4905.0,-0.71,0.1827,-0.8528,当前级别 (MMD: ['3buy'] Loss: 4905.0),3buy 止损
13,SHFE.ag2206,3sell,2022-02-21 13:40:00,2022-02-21 14:45:00,做空,4877.0,20.2994,4904.0,0.08,0.2871,-0.2050,当前级别 (MMD: ['3sell'] Loss: 4904.0),"3sell 当前级别出现买点（MMDS: []，BC：（BI: True, PZ: Fals..."
14,SHFE.ag2206,3buy,2022-02-22 10:55:00,2022-02-23 09:40:00,做多,4959.0,19.9637,4916.0,0.10,0.9276,-0.5041,当前级别 (MMD: ['3buy'] Loss: 4916.0),"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
15,SHFE.ag2206,3buy,2022-02-24 21:05:00,2022-02-24 21:50:00,做多,5185.0,19.0935,5096.0,-0.42,0.1350,-0.5593,当前级别 (MMD: ['3buy'] Loss: 5096.0),"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
16,SHFE.ag2206,l3buy,2022-02-25 01:25:00,2022-02-25 02:10:00,做多,5057.0,19.5768,5026.0,-0.16,0.0791,-0.2571,当前级别 (MMD: ['l3buy'] Loss: 5026.0),"l3buy 当前级别出现卖点（MMDS: ['3sell']，BC：（BI: False, ..."
17,SHFE.ag2206,3sell,2022-02-25 02:10:00,2022-02-25 14:25:00,做空,5049.0,19.6078,5061.0,1.41,1.9014,-0.0396,当前级别 (MMD: ['3sell'] Loss: 5061.0),"3sell 当前级别出现买点（MMDS: []，BC：（BI: True, PZ: Fals..."

In [7]:
# 显示历史持仓
orders_pd = BT.orders()
orders_pd

,datetime,type,price,amount,info
0,2022-02-07 23:00:00,buy,4781.0,20.7070,当前级别 (MMD: ['3buy'] Loss: 4767.0)
1,2022-02-08 09:00:00,sell,4798.0,20.7070,"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
2,2022-02-08 23:00:00,buy,4822.0,20.5309,当前级别 (MMD: ['3buy'] Loss: 4783.0)
3,2022-02-09 00:00:00,sell,4819.0,20.5309,"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
4,2022-02-12 01:00:00,buy,4816.0,20.5565,当前级别 (MMD: ['3buy'] Loss: 4799.0)
5,2022-02-12 01:50:00,sell,4820.0,20.5565,"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
6,2022-02-14 13:55:00,buy,4904.0,20.1876,当前级别 (MMD: ['3buy'] Loss: 4892.0)
7,2022-02-14 21:05:00,buy,4913.0,20.1506,当前级别 (MMD: ['l3buy'] Loss: 4898.0)
8,2022-02-15 11:20:00,sell,4941.0,20.1876,"3buy 当前级别出现卖点（MMDS: ['1sell']，BC：（BI: True, PZ..."
9,2022-02-15 11:20:00,sell,4941.0,20.1506,"l3buy 当前级别出现卖点（MMDS: ['1sell']，BC：（BI: True, P..."
10,2022-02-15 11:20:00,buy,4941.0,20.0364,当前级别 (MMD: ['1sell'] Loss: 4964.0)
11,2022-02-15 22:15:00,sell,4797.0,20.0364,"1sell 当前级别出现买点（MMDS: ['l3buy']，BC：（BI: False, ..."
12,2022-02-15 22:15:00,buy,4797.0,20.6379,当前级别 (MMD: ['l3buy'] Loss: 4780.0)
13,2022-02-16 00:25:00,sell,4793.0,20.6379,"l3buy 当前级别出现卖点（MMDS: ['3sell']，BC：（BI: False, ..."
14,2022-02-16 00:25:00,buy,4793.0,20.6551,当前级别 (MMD: ['3sell'] Loss: 4802.0)
15,2022-02-16 00:40:00,buy,4801.0,20.6207,当前级别 (MMD: ['l3buy'] Loss: 4777.0)
16,2022-02-16 00:55:00,sell,4804.0,20.6551,3sell 止损
17,2022-02-16 01:15:00,sell,4801.0,20.6207,"l3buy 当前级别出现卖点（MMDS: ['3sell']，BC：（BI: False, ..."
18,2022-02-16 01:15:00,buy,4801.0,20.6207,当前级别 (MMD: ['3sell'] Loss: 4808.0)
19,2022-02-16 02:15:00,sell,4811.0,20.6207,3sell 止损
20,2022-02-17 22:35:00,buy,4873.0,20.3160,当前级别 (MMD: ['3buy'] Loss: 4857.0)
21,2022-02-18 09:40:00,sell,4886.0,20.3160,"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
22,2022-02-18 21:50:00,buy,4925.0,20.1015,当前级别 (MMD: ['2sell'] Loss: 4945.0)
23,2022-02-18 22:45:00,sell,4925.0,20.1015,"2sell 当前级别出现买点（MMDS: ['3buy']，BC：（BI: False, P..."
24,2022-02-18 22:45:00,buy,4925.0,20.1015,当前级别 (MMD: ['3buy'] Loss: 4905.0)
25,2022-02-21 09:15:00,sell,4890.0,20.1015,3buy 止损
26,2022-02-21 13:40:00,buy,4877.0,20.2994,当前级别 (MMD: ['3sell'] Loss: 4904.0)
27,2022-02-21 14:45:00,sell,4873.0,20.2994,"3sell 当前级别出现买点（MMDS: []，BC：（BI: True, PZ: Fals..."
28,2022-02-22 10:55:00,buy,4959.0,19.9637,当前级别 (MMD: ['3buy'] Loss: 4916.0)
29,2022-02-23 09:40:00,sell,4964.0,19.9637,"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
30,2022-02-24 21:05:00,buy,5185.0,19.0935,当前级别 (MMD: ['3buy'] Loss: 5096.0)
31,2022-02-24 21:50:00,sell,5163.0,19.0935,"3buy 当前级别出现卖点（MMDS: []，BC：（BI: True, PZ: False..."
32,2022-02-25 01:25:00,buy,5057.0,19.5768,当前级别 (MMD: ['l3buy'] Loss: 5026.0)
33,2022-02-25 02:10:00,sell,5049.0,19.5768,"l3buy 当前级别出现卖点（MMDS: ['3sell']，BC：（BI: False, ..."
34,2022-02-25 02:10:00,buy,5049.0,19.6078,当前级别 (MMD: ['3sell'] Loss: 5061.0)
35,2022-02-25 14:25:00,sell,4978.0,19.6078,"3sell 当前级别出现买点（MMDS: []，BC：（BI: True, PZ: Fals..."

In [8]:
# 展示图表
BT.show_charts(BT.codes[0], BT.frequencys[0])